version: "3.8"
services: 
    client:
        build:
            context: ./client
            dockerfile: dockerfile.prod
        restart: unless-stopped
    api:
        build: 
            context: ./api
            dockerfile: dockerfile.prod
        environment: 
           - NODE_ENV=production
           - MONGO_USERNAME
           - MONGO_PWD
        restart: unless-stopped
        # depends_on: 
        #     - db
    db:
        image: mongo
        volumes: 
            - type: volume
              source: dbprod
              target: /data/db
        environment: 
            - MONGO_INIT_ROOT_USERNAME
            - MONGO_INIT_ROOT_PASSWORD
        restart: unless-stopped
    reverse_proxy:
        build:
            context: ./reverse-proxy
            dockerfile: dockerfile.prod
        ports: 
            - 80:80
            - 443:443
        restart: unless-stopped
        depends_on: 
            - api
            - db
            - client
        volumes: 
            - type: bind
              source: /etc/letsencrypt
              target: /etc/letsencrypt
volumes: 
    dbprod:
        external: true 



    